# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.example.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'example', 'function_path': 'animated_java:example/animations/animation_model_new/stop'}
tag @s remove aj.example.animation.animation_model_new.playing
scoreboard players set @s aj.animation_model_new.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:example/animations/animation_model_new/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only